# Generated by Django 2.2.4 on 2019-09-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtactt',
            new_name='econtact',
        ),
    ]
